name: Git Repository Sync
description: Sync current repository to a remote repository on GitHub, GitLab, AWS CodeCommit, etc.
author: NetEngine
inputs:
  ssh_private_key:
    description: SSH private key for ssh connection to the target repository
    required: false
  target_repo_url:
    description: Target git repository URL
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
